galaxy_info:
  author: Michael Rice
  description: Installation and setup of horizon metadatasearch dashboard
  company: Rackspace
  license: Apache2
  min_ansible_version: 1.6.6
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - cloud
    - python
    - horizon
    - heat
    - development
    - openstack
