horizon_metadatasearch_git_repo: https://github.com/michaelrice/horizon_metadata_search
horizon_metadatasearch_git_install_branch: master
horizon_metadatasearch_dest_dir: /opt/rackspace/horizon-metadatasearch
horizon_metadatasearch_pip_packages: []
horizon_venv_bin: "/openstack/venvs/horizon-{{ openstack_release }}/bin"
horizon_venv_lib_dir: "{{ horizon_venv_bin | dirname }}/lib/python2.7/site-packages"
